plugins:
  quick_message_enabled:
    default: true
    client: true
  quick_message_user_preference:
    default: false
    client: true
  quick_message_rate_limit_create:
    default: 1
    client: true
  quick_message_min_post_length:
    default: 1
    client: true
  quick_message_icon:
    default: 'envelope'
    client: true
  quick_message_required_badge:
    default: 0
    client: true
    enum: SettingQuickMessagesBadge
  quick_message_mobile:
    default: true
    client: true
